[package]
name    = "rustman"
version = "1.0.0"
edition = "2024"

[[bin]]
name = "rustman"
path = "rustman/main.rs"

[profile.dev]
strip = true

[profile.release]
codegen-units = 1
opt-level = 3
lto = "fat"
