[project.urls]
GitHub = "https://github.com/BrokenSource/Rustbin"

[project]
name        = "rustbin"
description = "Fast rustup shims for python"
authors     = [{name="Tremeschin"}]
dynamic     = ["keywords"]
version     = "1.28.2"
readme      = ".github/readme.md"
license     = {text="MIT OR Apache-2.0"}
requires-python = ">=3,<4"

# Ignore on monorepo
[tool.uv]
managed = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
exclude = ["*"]

[tool.hatch.metadata.hooks.custom]
path = "rustbin/build.py"

[tool.hatch.build.hooks.custom]
path = "rustbin/build.py"
dependencies = [
    # Networking, helpers
    "requests-cache",
    "attrs",
    "uv",
    # Easy cross compilation
    "cargo-zigbuild",
    "ziglang",
]

[dependency-groups]
dev = [
    "requests-cache",
    "hatchling",
    "attrs",
]
