[project.urls]
GitHub = "https://github.com/BrokenSource/Rustman"

[project]
name        = "rustman"
description = "Fast rustup shims for python"
authors     = [{name="Tremeschin"}]
version     = "1.28.2.0"
readme      = ".github/readme.md"
license     = {text="MIT OR Apache-2.0"}
requires-python = ">=3,<4"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["rustman"]
exclude = ["*.rs"]

[tool.hatch.build.hooks.custom]
path = "rustman/build.py"
dependencies = [
    # Networking, helpers
    "requests-cache",
    "attrs",
    "uv",
    # Easy cross compilation
    "cargo-zigbuild",
    "ziglang",
]

[dependency-groups]
dev = [
    "hatchling",
    "requests-cache",
    "attrs",
]
