[project]
name        = "rustman"
description = "Fast rustup shims for python"
authors     = [{name="Tremeschin"}]
version     = "1.28.2.0"
readme      = "readme.md"
requires-python = ">=3.9"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["rustman"]

[tool.hatch.build.hooks.custom]
path = "build.py"
dependencies = [
    "requests-cache",
    "packaging",
]

[dependency-groups]
dev = [
    "requests-cache",
    "packaging",
]
