name: release
on:
  workflow_dispatch:
    inputs:
      wheels:
        required: true
        type: boolean
      pypi:
        required: true
        type: boolean

permissions:
  contents: write

jobs:
  main:
    name: Make wheels
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Make wheels
        if: ${{inputs.wheels || inputs.pypi}}
        run: uv run rustman/build.py

      - name: Upload wheels
        if: ${{inputs.wheels || inputs.pypi}}
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist/*

      - name: Publish wheels
        if: ${{inputs.pypi}}
        run: uv publish
