on:
  workflow_dispatch:
    inputs:
      publish:
        required: true
        type: boolean

permissions:
  contents: write

jobs:
  main:
    name: Make wheels
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Make wheels
        run: uv run rustbin/build.py

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist/*

      - name: Publish wheels
        if: ${{inputs.publish}}
        run: uv publish
